### ISSUE TITLE
Capture requirements for account lifecycle process

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/adjutant-moc#13]
Document our business requirements for account lifecycle:

- How/when are accounts created?
- How/when do accounts expire?
- How we we manage exceptions to standard workflow?
- Etc.

**Comment by rob-baron** [comment]
There needs to be 2 parts to this:

    1) Adjutant should know how to delete everything that it added to a particular project.

    2) Reporting needs a verification part that identifies all allocated resources.  Zombie resources should be reported on for possible deletion.  Changes made to quota or accounts created should be passed to the approval process.
