### ISSUE TITLE
Investigate ssh connection issues to mail server from sso2

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/adjutant-moc#17]
The ssh connection to the mail server works from sso1 but not from sso2.

**Comment by larsks** [comment]
@knikolla can you provide some more details here? From either `sso1` or `sso2` I can successfully `ssh mail.massopen.cloud`.

**Comment by knikolla** [comment]
Copying from @larsks on Slack:

Looking at the nat table, the following is in the PREROUTING chain:
```
-P PREROUTING ACCEPT
-A PREROUTING -p tcp -m tcp --dport 2228 -j DNAT --to-destination 128.31.28.12:22
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
```
That first rule there, meant to enable access to sso2 on port 2228, also matches outbound traffic on port 2228 and redirects it to the local host.

the best "quick fix" is to modify those PREROUTING rules to require a matching destination address.
