### ISSUE TITLE
Enable quota management for Kaizen OpenStack

### ISSUE THREAD

**Issue by knikolla** [CCI-MOC/adjutant-moc#18]
Currently, Adjutant already supports a dashboard and API for requesting quota changes. Enable the feature for Kaizen OpenStack.

- [ ] Wrap through `adjutant-moc`
- [ ] Write tests
- [ ] Enable dashboard
- [ ] Test
- [ ] Release
- [ ] Deploy

**Comment by msdisme** [comment]
Using as an example for Acceptance Criteria:
Currently, Adjutant already supports a dashboard and API for requesting quota changes. Enable the feature for Kaizen OpenStack.

- [ ] Wrap through `adjutant-moc`
     - definition of done?
- [ ] Write tests  
     - definition of done  
- [ ] Enable dashboard
- [ ] Test
     - Tests run in production
     - pipeline set up in Git to test any changes

- [ ] Release
     - user documentation written and reviewed on test system
     - 
- [ ] Deploy

Acceptance Criteria: 
List Quota, Create Quota, Delete Quota, Presentation via Dashboard
