### ISSUE TITLE
Proxy error when approving multiple account requests

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/adjutant-moc#5]
Proxy error (attached) when approving ~ 8 users. 
<img width="859" alt="Screen Shot 2020-11-18 at 3 37 48 PM" src="https://user-images.githubusercontent.com/6126065/99585886-ef441280-29b4-11eb-9580-da76d61d04ec.png">

**Comment by knikolla** [comment]
We're phasing out Adjutant in favor of ColdFront.
