### ISSUE TITLE
Onboarding Architecture Discussion

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/adjutant-moc#6]
eg. threading model of adjutant not updated yet. 

Attendees: Whole team discussion  time boxed at 2 hours.  Kristi to do a sketch first.  2nd week of sprint.  @knikolla please get on folks calendar soon.  Also, mechanism to capture discussion so we don't lose thread over holidays.

**Comment by msdisme** [comment]
schedule nudge - @knikolla if you want to grab 2 hours by end of sprint it will need to be scheduled soon

**Comment by knikolla** [comment]
Thanks for the nudge. I am planning to do an initial sketch out later today. For the whole team discussion, I'm planning on sending a calendar invite for next week, so this'll happen in the next sprint.

**Comment by msdisme** [comment]
@knikolla I recommend scheduling a meeting for this week as a forcing function :-).

**Comment by knikolla** [comment]
The action out of this meeting was to gather requirements from stakeholder in the MOC and NERC. These actions items will be captured and groomed as issues during the next backlog grooming meeting.
