### ISSUE TITLE
Adjutant should notify project requestor if project name already exists

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/adjutant-moc#8]
Adjutant should notify project requestor if project name already exists.  It should also clarify that a. if they are trying to be added to an existing project to have that project owner follow these instructions .... https://support.massopen.cloud/kb/faq.php?id=22  b. if not they will need to rename the project.

**Comment by knikolla** [comment]
We're phasing out Adjutant in favor of ColdFront.
